version: "3.5"
services:
  angular:
    container_name: angular
    build: ./public_html/
    #working_dir: /home/$USER/public_html
    ports:
      - 4200:4200
    restart: unless-stopped
  nginx:
    container_name: nginx
    depends_on:
      - angular
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: unless-stopped